apiVersion: batch/v1
kind: Job
metadata:
  {{- with .Values.lowops.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "lowops.labels" . | nindent 4 }}
  name: {{ include "lowops.fullname" . }}
spec:
  template:
    metadata:
      labels:
        {{- include "lowops.labels" . | nindent 8 }}
      name: {{ include "lowops.fullname" . }}
    spec:
      containers:
      - env:
        - name: ROLES
          value: {{ .Values.lowops.jobEnv.roles }}
        - name: LOW_OPS_ENV
          value: {{ .Values.lowops.jobEnv.environment }}
        - name: CONTAINER_IMAGE
          value: {{ .Values.lowops.image.containerImage }}
        - name: BASE_DOMAIN
          value: {{ .Values.lowops.jobEnv.baseDomain }}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        volumeMounts:
          - name: values-secret
            mountPath: /secret
        image: {{ .Values.lowops.image.containerImage }}
        imagePullPolicy: {{ .Values.lowops.image.pullPolicy }}
        name: ansible
        resources:
          {{- toYaml .Values.lowops.resources | nindent 10 }}
      volumes:
        - name: values-secret
          secret:
            secretName: {{ include "lowops.fullname" . }}-values
      {{- if .Values.lowops.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.lowops.imagePullSecrets | nindent 6 }}
      {{- end }}
      serviceAccount: {{ include "lowops.fullname" . }}-sa
      serviceAccountName: {{ include "lowops.fullname" . }}-sa
      terminationGracePeriodSeconds: 30
      restartPolicy: {{ .Values.lowops.restartPolicy }}
      {{- with .Values.lowops.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lowops.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lowops.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
