apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.lowops.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "lowops.labels" . | nindent 4 }}
  name: {{ include "lowops.fullname" . }}-values
type: Opaque
data:
  values.yaml: |-
    {{- include "lowops.platformConfig" . | b64enc | nindent 4 -}}