{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lowops.serviceAccountName" . }}-sa
  labels:
    {{- include "lowops.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.lowops.imagePullSecrets }}
automountServiceAccountToken: true
imagePullSecrets: {{ toYaml .Values.lowops.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
