{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
data:
  postgres-username: {{ .Values.secret.username | b64enc | quote }}
  postgres-password: {{ .Values.secret.password | b64enc | quote }}
  postgres-host: {{ .Values.secret.backupHost | b64enc | quote }}
metadata:
  name: {{ include "kanister-actionset.secretName" . }}
  labels:
    {{- include "kanister-actionset.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
