apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-nextjs.fullname" . }}
  labels:
    {{- include "app-nextjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app-nextjs.selectorLabels" . | nindent 4 }}
