{{- if .Values.autoscale.enabled -}}
{{- $serviceName := include "app-mendix.fullname" . -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app-mendix.fullname" . }}
  labels:
    {{- include "app-mendix.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app-mendix.fullname" . }}-slave
  minReplicas: {{ .Values.autoscale.minSlaveReplicas }}
  maxReplicas: {{ .Values.autoscale.maxSlaveReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscale.targetCPUUtilizationPercentage }}
{{- end }}
