{{- if and (eq (printf "%v" .Values.ingress.enabled) "true") .Values.ingress.hosts }}
{{- $serviceName := include "app-mendix.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $className := .Values.ingress.ingressClassName -}}
{{- $globalAnnotations := .Values.ingress.annotations | default dict -}}
{{- range $host := .Values.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $.Release.Name ($host.id | toString | lower) }}
  labels:
    {{- include "app-mendix.labels" $ | nindent 4 }}
  {{- $annotations := mustMergeOverwrite (deepCopy $globalAnnotations) ($host.annotations | default dict) }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $host.ingressClassName | default $className }}
  rules:
    - host: {{ $host.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            path: {{ $host.path | default "/" }}
            pathType: Prefix
  {{- if and $host.tls $host.tls.secretName (eq (printf "%v" $host.tls.enabled) "true") }}
  tls:
    - hosts:
        - {{ $host.host }}
      secretName: {{ $host.tls.secretName }}
  {{- end }}
{{- end }}
{{- end }}
