---
{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app-mendix.fullname" . }}
  labels:
    {{- include "app-mendix.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | b64enc | quote}}
{{- end }}
{{- end }}