apiVersion: v1
kind: Service
metadata:
  name: {{ template "app-mendix.fullname" . }}
  labels:
    {{- include "app-mendix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    {{- include "app-mendix.selectorLabels" . | nindent 6 }}
