---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "retraced.fullname" . }}-mmdbdir
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    retraceddev: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
