---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retraced.fullname" . }}-api
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app: auditlog
    retraceddev: "1"
stringData:
  ADMIN_ROOT_TOKEN: {{ .Values.api.secret.ADMIN_ROOT_TOKEN }}
  API_BASE_URL_PATH: /auditlog
  API_TOKEN: ""
  DB_TOKEN: ""
  GEOIPUPDATE_ACCOUNT_ID: ""
  GEOIPUPDATE_DB_DIR: /etc/mmdb
  GEOIPUPDATE_EDITION_IDS: GeoLite2-City
  GEOIPUPDATE_FREQUENCY: "168"
  GEOIPUPDATE_LICENSE_KEY: ""
  GEOIPUPDATE_USE_MMDB: ""
  GEOIPUPDATE_VERBOSE: "1"
  HMAC_SECRET_ADMIN: ""
  HMAC_SECRET_VIEWER: ""
  LOG_LEVEL: info
  MANDRILL_KEY: ""
  NSQD_HOST: {{ include "retraced.fullname" . }}-nsqd
  NSQD_HTTP_PORT: "4151"
  NSQD_TCP_PORT: "4150"
  POSTGRES_DATABASE: {{ .Values.api.secret.POSTGRES_DATABASE }}
  POSTGRES_HOST: {{ .Values.api.secret.POSTGRES_HOST }}
  POSTGRES_PASSWORD: {{ .Values.api.secret.POSTGRES_PASSWORD }}
  POSTGRES_POOL_SIZE: "10"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.api.secret.POSTGRES_USER }}
  PG_SEARCH: {{ quote .Values.api.secret.PG_SEARCH }}
  PROCESSOR_TOKEN: ""
  RETRACED_API_BASE: http://localhost:3000/auditlog
  RETRACED_DISABLE_GEOSYNC: ""
  STAGE: ""
  STATSD_HOST: ""
  STATSD_PORT: ""
