---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-nsqd
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app: auditlog
    retraceddev: "1"
    tier: nsq
spec:
  ports:
  - name: tcp
    port: 4150
    targetPort: 4150
  - name: http
    port: 4151
    targetPort: 4151
  selector:
    app: auditlog
    retraceddev: "1"
    tier: nsq
  type: ClusterIP
