---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retraced.fullname" . }}-admin-portal
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app: adminportal
    retraceddev: "1"
stringData:
  BOXYHQ_LICENSE_KEY: {{ .Values.adminPortal.secret.BOXYHQ_LICENSE_KEY }}
  DB_CLEANUP_LIMIT: {{ .Values.adminPortal.secret.DB_CLEANUP_LIMIT }}
  DB_ENCRYPTION_KEY: {{ .Values.adminPortal.secret.DB_ENCRYPTION_KEY }}
  DB_TTL: {{ .Values.adminPortal.secret.DB_TTL }}
  DB_TYPE: {{ .Values.adminPortal.secret.DB_TYPE }}
  DB_URL: {{ .Values.adminPortal.secret.DB_URL }}
  JACKSON_API_KEYS: {{ .Values.adminPortal.secret.JACKSON_API_KEYS }}
  NEXTAUTH_ACL: {{ .Values.adminPortal.secret.NEXTAUTH_ACL }}
  NEXTAUTH_JWT_SIGNING_PRIVATE_KEY: {{ .Values.adminPortal.secret.NEXTAUTH_JWT_SIGNING_PRIVATE_KEY }}
  NEXTAUTH_SECRET: {{ .Values.adminPortal.secret.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: {{ .Values.adminPortal.secret.NEXTAUTH_URL }}
  RETRACED_ADMIN_ROOT_TOKEN: {{ .Values.adminPortal.secret.RETRACED_ADMIN_ROOT_TOKEN }}
  RETRACED_EXTERNAL_URL: http://{{ include "retraced.fullname" . }}-api:3000/auditlog
  RETRACED_HOST_URL: http://{{ include "retraced.fullname" . }}-api:3000/auditlog
  SAML_AUDIENCE: {{ .Values.adminPortal.secret.SAML_AUDIENCE }}
  SMTP_FROM: {{ .Values.adminPortal.secret.SMTP_FROM }}
  SMTP_HOST: {{ .Values.adminPortal.secret.SMTP_HOST }}
  SMTP_PASSWORD: {{ .Values.adminPortal.secret.SMTP_PASSWORD }}
  SMTP_PORT: {{ .Values.adminPortal.secret.SMTP_PORT }}
  SMTP_USER: {{ .Values.adminPortal.secret.SMTP_USER }}
