---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retraced.fullname" . }}-admin-portal
  labels:
    {{- include "retraced.labels" . | nindent 4 }}
    app: auditlog
    retraceddev: "1"
    tier: admin-portal
spec:
  ports:
  - name: http
    port: 5225
    targetPort: 5225
  selector:
    app: auditlog
    retraceddev: "1"
    tier: admin-portal
  type: ClusterIP
