apiVersion: v2
name: app-nextjs
description: A Helm chart for deploying a nextjs applications on low-ops platform
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: app-generic
    version: 0.1.6
    repository: https://cinaq.github.io/helm-charts